trunk/toolbar_buttons_web/tbutton_votes/urls.py
from django.conf.urls import patterns, url, include

from toolbar_buttons.toolbar_buttons_web.tbutton_votes import views
from upvotes import views as upvotes_views

urlpatterns = patterns('', 
    url(r'^$', views.RequestTbuttonList.as_view(), name='tbutton-request'),
    url(r'^page/(?P<page>\d+)/$', views.RequestTbuttonList.as_view(), name='tbutton-request'),
    url(r'^(?P<request_id>\d+)/$', views.TbuttonRequestView.as_view(), name='tbutton-request'),
    url(r'^follow/$', views.TbuttonRequestFollow.as_view(), name='tbutton-request-follow'),
    url(r'^make/$', views.MakeTbuttonRequet.as_view(), name='tbutton-request-make'),
    url(r'^spam/$', upvotes_views.request_spam, name='tbutton-request-spam'),
    url(r'^comment/spam/$', upvotes_views.comment_spam, name='tbutton-request-comment-spam'),
    url(r'^vote/$', views.TbuttonRequestVote.as_view(), name='tbutton-request-vote'),
)

trunk/toolbar_buttons_web/tbutton_votes/models.py
from django.db import models
from django.contrib.auth.models import User
from upvotes.models import AbstractRequest, AbstractRequestComment
from djangopress.core.format import format_markdown

class TbuttonRequest(AbstractRequest):
    
    APPLICATIONS = (
        ('FX', 'Firefox'),
        ('TB', 'Thunderbird'),
        ('OT', 'Other'),
    )
    
    application = models.CharField(choices=APPLICATIONS, max_length=2)
    subscriptions = models.ManyToManyField(User, null=True, blank=True, related_name='tbutton_request_subscriptions')
      
    def get_message(self):
        return format_markdown(self.message)
    
    def get_absolute_url(self, page=None):
        if page == None:
            page = TbuttonRequest.objects.filter(is_spam=False, is_public=True, posted__lt=self.posted).order_by('-votes', '-posted').count()/10 + 1
        if page == 1:
            return reverse("tbutton-request")
        return reverse("tbutton-request", kwargs={'page': page})
    
    def get_comments(self):
        return TbuttonRequestComment.objects.filter(request=self, is_public=True, is_spam=False)
       
class TbuttonRequestComment(AbstractRequestComment):
    request = models.ForeignKey(TbuttonRequest, related_name='comments')

trunk/toolbar_buttons_web/tbutton_votes/views.py
from django.shortcuts import render

from toolbar_buttons.toolbar_buttons_web.tbutton_votes.models import TbuttonRequest, TbuttonRequestComment

from upvotes.views import MakeRequest, RequestList, RequestView, RequestVote, RequestFollow
from upvotes.forms import get_request_form, get_anon_request_form, get_request_comment_form, get_anon_request_comment_form

TbuttonRequestForm = get_request_form(TbuttonRequest, ('application', ))
TbuttonRequestAnonymousForm = get_anon_request_form(TbuttonRequest, ('application', ))
TbuttonRequestCommentForm = get_request_comment_form(TbuttonRequestComment)
TbuttonRequestCommentAnonymousForm = get_anon_request_comment_form(TbuttonRequestComment)

class MakeTbuttonRequet(MakeRequest):
    template = 'tbutton_votes/make.html'
    title = "Make a Toolbar Button Request"
    request_url = 'tbutton-request'
    spam_url = 'tbutton-request-spam'
    request_form = TbuttonRequestForm
    request_anonymous_form = TbuttonRequestAnonymousForm
    
class TbuttonRequestView(RequestView):
    template = 'tbutton_votes/request.html'
    request_class = TbuttonRequest
    spam_url = 'tbutton-comment-spam'
    request_url = 'tbutton-request'
    comment_form = TbuttonRequestCommentForm
    comment_anonymous_form = TbuttonRequestCommentAnonymousForm
  
class TbuttonRequestVote(RequestVote):
    request_class = TbuttonRequest
    session_id = 'tbutton-voted-%s'
    request_url = 'tbutton-request'
    duplicate_vote_message = "You can not up vote a button request multiple times."

class TbuttonRequestFollow(RequestFollow):
    request_class = TbuttonRequest
    request_url = 'tbutton-request'

    def get_subscriptions(self, request):
        return request.user.tbutton_request_subscriptions

class RequestTbuttonList(RequestList):
    template = 'tbutton_votes/index.html'
    title = "Toolbar Button Requests"
    request_class = TbuttonRequest

trunk/toolbar_buttons_web/tbutton_votes/templates/tbutton_votes/index.html
{% extends "base.html" %}
{% load static %}
{% load show_pagination %}

{% block head_tags %}
    <link type="text/css" rel="stylesheet" href="{% get_static_prefix %}css/upvote.css">
    <link type="text/css" rel="stylesheet" href="{% get_static_prefix %}css/upvotes/jquery-ui.css">
    <script type="text/javascript" src="{% get_static_prefix %}js/upvotes/jquery-ui.js"></script>
{% endblock %}

{% block content %}

<div class="content-box">
    <a href="/toolbar_button/">Toolbar Buttons</a> &bull; <a href="{% url 'tbutton-request' %}">Button Requets</a>
</div>

<h1>Toolbar Button Requets</h1>

<p>
    Welcome to Toolbar Button Requets.  Here you can see what others have asked for, and vote for there requests, or follow the request meaning you will be notified when the request is implemented.  Finally you can <a href="{% url 'tbutton-request-make' %}">make a new button request</a>.
</p>

{% for request in page %}
<div class="content-box upvote-request">
    <h3 id="request-{{ request.pk }}"><a href="{% url 'tbutton-request' request_id=request.pk %}">{{ request.title }}</a></h3>
    <small>{{ request.posted }} by {{ request.author_name }}</small>
    <div>
        {% if request.closed %}
            <div class="votes"><span class="vote">{{ request.votes }}</span> Votes</div>
        {% else %}
            <form method="post" action="{% url 'tbutton-request-vote' %}" class="votes content-box">
                {% csrf_token %}
                <input type="hidden" value="{{ request.pk }}" name="request" />
                <button class="vote-link" type="submit"><span class="vote">{{ request.votes }}</span> Vote up</button>
             </form>
        {% endif %}
    </div>
    <div class="request-message">
        {{ request.get_message }}
        {% if request.application %}
        <hr />
        <p>
            Request is for: {{ request.get_application_display }}
        </p>
        {% endif %}
        {% if request.closed %}
            <hr />
            <p>This has been closed because: {{ request.close_reason }}.</p>
        {% endif %}
        <form method="post" action="{% url 'pastel-svg-request-follow' %}" class="follow content-box">
            {% csrf_token %}
            <input type="hidden" value="{{ request.pk }}" name="request" />
            <button type="submit">Follow</button>            
        </form>
    </div>
    <div class="content-box">
        <h3>Comments</h3>
        {% for comment in upvote_request.get_comments %}
            <p class="request-comment">{{ comment.message }} - {{ comment.author_name }} at {{ comment.posted }}</p>
            <hr />
        {% empty %}
            <p>There are no comments.</p>
        {% endfor %}
        <p>
        <a href="{% url 'tbutton-request' request_id=request.pk %}#comment">Make Comment</a>
        </p>
    </div>
</div>
<script type="text/javascript" src="{% get_static_prefix %}js/upvotes.js"></script>

{% empty %}
    <p>Currently no toolbar button requests have been made, be the first to ask!</p>
{% endfor %}

{% show_pagination page first_request %}

{% endblock %}

trunk/toolbar_buttons_web/tbutton_votes/templates/tbutton_votes/make.html
{% extends "base.html" %}
{% load field_form %}

{% block content %}

<div class="content-box">
    <a href="/toolbar_button/">Toolbar Button</a> &bull; <a href="{% url 'tbutton-request' %}">Toolbar Button Requets</a> &bull; Make new toolbar button request
</div>

    <h1>Toolbar Buttons Requests</h1>
    <p>
        Please describe the button that you would like added as best as you can.  If similar funtional already exist in a menu item, mention where to find it.  Or if an extension has something similar, please mention it.
    </p>
    <p> Please note that requests will be rejected if:</p>
    <ul>
        <li>They ask for button that open web pages, use the <a href="/toolbar_button/link-button-maker/">Link Button Maker</a> instead.</li>
        <li>They would depend on another extension to work.  It is better to ask the developer of that extension to add the button.</li>
    </ul>
    <form action="{% url 'tbutton-request-make' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {% if not request.user.is_authenticated %}
        <p><small>Please note that you are not <a href="{% url 'login' %}?next={{request.path}}">logged in</a>.  This request will not be connected to your account, and you will not be notified when it is implemented.</small></p>
        {% endif %}
        {% form form %}
        <input type="submit" value="Submit Request">
    </form>
    <p>
        <small>Please note the format used for display the message is markdown.</small>
    </p>
{% endblock %}

trunk/toolbar_buttons_web/tbutton_votes/templates/tbutton_votes/request.html
{% extends "base.html" %}
{% load static %}
{% load field_form %}

{% block head_tags %}
    <link type="text/css" rel="stylesheet" href="{% get_static_prefix %}css/upvote.css">
    <link type="text/css" rel="stylesheet" href="{% get_static_prefix %}css/upvotes/jquery-ui.css">
    <script type="text/javascript" src="{% get_static_prefix %}js/upvotes/jquery-ui.js"></script>
{% endblock %}

{% block content %}

<div class="content-box">
    <a href="/toolbar_button/">Toolbar Buttons</a> &bull; <a href="{% url 'tbutton-request' %}">Toolbar Button Requets</a> &bull; {{ upvote_request.title }}
</div>

<div class="content-box upvote-request">
    <h1 id="request-{{ upvote_request.pk }}">{{ upvote_request.title }}</h1>
    <small>{{ upvote_request.posted }} by {{ upvote_request.author_name }}</small>
    <div>
        {% if upvote_request.closed %}
            <div class="votes"><span class="vote">{{ upvote_request.votes }}</span> Votes</div>
        {% else %}
            <form method="post" action="{% url 'tbutton-request-vote' %}" class="votes content-box">
                {% csrf_token %}
                <input type="hidden" value="{{ upvote_request.pk }}" name="request" />
                <button class="vote-link" type="submit"><span class="vote">{{ upvote_request.votes }}</span> Vote up</button>
             </form>
        {% endif %}
        <form method="post" action="{% url 'pastel-svg-request-follow' %}" class="follow content-box">
            {% csrf_token %}
            <input type="hidden" value="{{ upvote_request.pk }}" name="request" />
            <button type="submit">Follow</button>            
        </form>
    </div>
    <div class="request-message">
        {{ upvote_request.get_message }}
        {% if upvote_request.concept_icon %}
        <hr />
        <p>
            Concept Icon: <img src="{{ upvote_request.concept_icon.url }}" alt="">
        </p>
        {% endif %}
        {% if upvote_request.closed %}
            <hr />
            <p>This has been closed because: {{ upvote_request.close_reason }}.</p>
        {% endif %}
        <form method="post" action="{% url 'tbutton-request-follow' %}" class="follow content-box">
            {% csrf_token %}
            <input type="hidden" value="{{ upvote_request.pk }}" name="request" />
            <button type="submit">Follow</button>            
        </form>
    </div>
    <div class="content-box">
        <h3>Comments</h3>
        {% for comment in upvote_request.get_comments %}
            <p class="request-comment">{{ comment.message }} - {{ comment.author_name }} at {{ comment.posted }}</p>
            <hr />
        {% empty %}
            <p>There are no comments.</p>
        {% endfor %}
        <form id="comment" method="post" action="{% url 'tbutton-request' request_id=upvote_request.pk %}">
            {% csrf_token %}
            {% form form %}
            <input type="submit" value="Submit Comment">
        </form>
    </div>
</div>
<script type="text/javascript" src="{% get_static_prefix %}js/upvotes.js"></script>
{% endblock %}